name: breathin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  logger: ^2.5.0
  connectivity_plus: ^6.1.2
  fluttertoast: ^8.2.10
  intl: ^0.20.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  modal_progress_hud_nsn: ^0.5.1
  purchases_flutter: ^8.4.2
  shared_preferences: ^2.3.5
  file_picker: ^8.1.7
  audioplayers: ^6.1.0
  freezed_annotation: ^2.4.4
  json_serializable: ^6.7.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:

  uses-material-design: true
  assets:
    - assets/sound/trek_listening_1.mp3
    - assets/sound/trek_listening_2.mp3
    - assets/sound/trek_listening_3.mp3
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  